# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hybrid3D
email: hyuk.allen.kim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Graphics, Machine Learning, Quantum Computer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.hybrid3d.dev" # the base hostname & protocol for your site
github_username:  Hybrid3D
permalink: /:year/:month/:day/:title
google_analytics: UA-446868-7

# Build settings
markdown: kramdown

#theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

#kramdown:
#  parse_block_html: true

collections:
  category:
    output: true
    permalink: /:path/
  difficulty:
    output: true
    permalink: /difficulty/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments : true
theme: jekyll-theme-slate